const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  COMPANY_ADMIN: "COMPANY_ADMIN",
  SALES_MANAGER: "SALES_MANAGER",
  SALES_EXECUTIVE: "SALES_EXECUTIVE",
  CUSTOMER_SUPPORT: "CUSTOMER_SUPPORT",
  ACCOUNTANT: "ACCOUNTANT"
};

export default ROLES;
